# Generated by Django 5.2 on 2025-12-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking_successful_alter_invoice_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_successful',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='booking_successful',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
