# Generated by Django 5.2 on 2025-12-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_successful_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_at',
        ),
    ]
