# Generated by Django 5.2 on 2025-12-31 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_feedback_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_successful',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AddField(
            model_name='booking_successful',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='booking_successful',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
