# Generated by Django 5.2 on 2025-12-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_successful_message_booking_successful_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_successful',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
