# Generated by Django 5.2 on 2026-01-29 14:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_successful',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_successful',
            name='payment_status',
            field=models.CharField(default='Pay at Hotel', max_length=50),
        ),
    ]
