# Generated by Django 5.2 on 2026-01-29 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_booking_successful_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_successful',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 29, 19, 50, 45)),
            preserve_default=False,
        ),
    ]
