# Generated by Django 5.2 on 2026-01-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking_successful_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_successful',
            name='created_at',
        ),
    ]
