# Generated by Django 5.2 on 2026-02-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_booking_successful_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
