# Generated by Django 5.2 on 2026-02-01 09:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking_successful',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking_successful',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
