# Generated by Django 5.2 on 2026-02-01 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_booking_created_at_alter_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_successful',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
