"""
Django settings for hotel project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from logging import config
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$2*qdbg@!h5+p&ia5p8siwk1*=au8uo5zj_a-ycl*m9-wn76a0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'home.middleware.LogoutOnFirstVisitMiddleware',
]


ROOT_URLCONF = 'hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'newdb',
        'USER': 'vivek',
        'PASSWORD': 'Hello123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
# STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY','pk_test_51RN9tQ4CpgDuz9crfLymDWuPXHJGx8Fd1fX2slvb7kJoZBAhyVkGNgEzPOnaIxZV3vpdvSXsZCgJPJDatH2Db3br00zjnQaNXq')
# STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY','sk_test_51RN9tQ4CpgDuz9crroYfDD8LWInYnmKZiblcozJA3GH7VedA54Pi4sqci4FEPh3TjDAYj5rB2tizVY9gGGewYp8u00N4vE2aav')

# PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID','ATcFMrMkIz_IgJSNYB6lyusqwz2MhARukGg2F_P3MrFor-ek5kfUODLOCWwFbqvCcpOu41rYkPH912ZC')
# PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET','EGCtDzv-yfFPFO_QG5l-uT-FtkGkJQ9koDe1URXtfPha3A8GR1cJlFIrNWEZ6Ea7FfqOnw7vlx0ld7SE')    
# PAYPAL_MODE = 'sandbox'  # Change to 'live' for production
# # settings.py
# TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID','ACf2782ac8608b55c1d64f8529d3e8fcae')
# TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN','c47a9e81407dd4e77549288bfbee1b84')
# # TWILIO_PHONE_NUMBER = '+916295810903'  # Your Twilio phone number
# TWILIO_WHATSAPP_NUMBER = '+916295810903'  # Twilio's WhatsApp sandbox number

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST', 'smtp.gmail.com')  # or your provider
# EMAIL_PORT = config('EMAIL_PORT', 587)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', 'vivekmajumdar150@gmail.com')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', 'bwsv fqbl hhyx jgdp')
# LOGIN_URL = '/login/'  # Update this to the correct URL for your login page

from decouple import config

# Replace os.getenv with config
SECRET_KEY = config('DJANGO_SECRET_KEY', default='fallback-secret-key')
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_NUMBER = config('TWILIO_WHATSAPP_NUMBER', default='')
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')